spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/sns
  username: postgre
  password: posttest2023
  show-sql: true

spring:
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  redis:
    lettuce:
      pool:
        max-active: 5 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 5 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: localhost
    port: 6379


jwt:
  secret-key: hstar.sns-practice-2022.jwttoken.secret_key
  # 30 days
  token.expired-time-ms: 2592000000
